### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by nkv1995** [Alibaba-AAIG/Beyond-ImageNet-Attack#2]
https://github.com/Alibaba-AAIG/Beyond-ImageNet-Attack/blob/7e8b1b8ec5728ebc01723f2c444bf2d5275ee7be/DCL_finegrained/LoadModel.py#L6
`
`NameError: name 'pretrainedmodels' is not defined`

**Comment by qilong-zhang** [comment]
Hi @nkv1995 , this issue can be solved by `pip install pretrainedmodels`.

**Comment by nkv1995** [comment]
thank you.
