### ISSUE TITLE
cursor already registered in Tk_GetCursor Aborted (core dumped)

### ISSUE THREAD

**Issue by hoonsyang** [Alibaba-AAIG/Beyond-ImageNet-Attack#5]
python train.py --model_type vgg16 --RN False --DA False

I tried the above default training, but the error occurred at the end of the batch (epoch 1) training.
Can you help debug this please?

**Comment by qilong-zhang** [comment]
@hoonsyang Hi, could you paste the full information of this error? I gauss this error is cause by the version of your torch (yours may be not the same as ours).

**Comment by hoonsyang** [comment]
@qilong-zhang Thanks for the reply The full information is on the title. BTW, I tried once again, and there's no error at the moment. I'll let you know if it occurs again. Thanks:)
