### ISSUE TITLE
Why no netG_BIA+RN+DA_0.pth?

### ISSUE THREAD

**Issue by jiamingzhang94** [Alibaba-AAIG/Beyond-ImageNet-Attack#6]
There are 3 pre-trained weights for every backbone, BIA, BIA+RN and BIA+DA, yet lack of BIA+RN+DA. Why?

**Comment by qilong-zhang** [comment]
hi @jiamingzhang94 , we found in our paper that RN and DA are not well compatible, so we did not upload the related `.pth` file.
