### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by tanlingp** [Alibaba-AAIG/Beyond-ImageNet-Attack#7]
Can I only use imagenet to train the generator? The training set cannot be downloaded and used as it reaches 138G.

**Comment by qilong-zhang** [comment]
Hi @tanlingp , BIA is trained by ImageNet. What does "Can I only use imagenet to train the generator?" mean?

**Comment by tanlingp** [comment]
Can I use other datasets to train BIA?

**Comment by qilong-zhang** [comment]
Of course. You can use any dataset to train BIA. The case of modifying the source domain is also discussed in our paper Appendix A.5
